feat(installer): support noninteractive NAS setup

diff --git a/install/nas b/install/nas
--- a/install/nas
+++ b/install/nas
@@ -10,21 +10,27 @@ fail() {
     exit 1
 }
 
-hermes_option=
-case "$#" in
-    0) ;;
-    1)
+validate_arguments() {
+    hermes_option=
+    answers_file=
+    while [ "$#" -gt 0 ]; do
         case "$1" in
-            --enable-hermes|--disable-hermes) hermes_option=$1 ;;
-            *) fail "this installer accepts only --enable-hermes or --disable-hermes" ;;
+            --enable-hermes|--disable-hermes)
+                [ -z "$hermes_option" ] || fail "the Hermes mode may be selected only once"
+                hermes_option=$1
+                shift
+                ;;
+            --answers-file)
+                [ -z "$answers_file" ] || fail "the answers file may be selected only once"
+                [ "$#" -ge 2 ] && [ -n "$2" ] || fail "--answers-file requires a path"
+                answers_file=$2
+                shift 2
+                ;;
+            *) fail "this installer accepts only a Hermes mode and --answers-file PATH" ;;
         esac
-        ;;
-    *) fail "this installer accepts only --enable-hermes or --disable-hermes" ;;
-esac
-set --
-if [ -n "$hermes_option" ]; then
-    set -- "$hermes_option"
-fi
+    done
+}
+validate_arguments "$@"
 
 case $(uname -s) in
     Linux) platform=linux ;;
